
name:  makepdf

# Create pdf for all commits (perhaps should just do on main) 
on:
  push:
    branches:
      - "*"


jobs:
  # Update the TeX Live tree if necessary
  texlive-cache:
    runs-on: ubuntu-latest
    name: Update TeX Live
    outputs:
      cache_key: ${{ steps.texlive.outputs.cache_key }}
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        id: texlive
        uses: zauguin/install-texlive@v4
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
# just run lualatex-dev once while testing setup	  
      - name: latex
        run: lualatex-dev doc.tex
      - name: setup git config
        run: |
          # setup the username and empty email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        # recycle pdf branch with no history
        run: |
          # Stage the file, commit and push
          git checkout -b pdf
          git checkout --orphan newpdf
          git add doc.pdf
          git commit -m "new commit"
          git branch -D pdf
          git branch -m pdf
          git push  -f origin pdf
          git push --set-upstream origin pdf

# artifact alternative not currently used
#      - name: Upload PDF
#        uses: actions/upload-artifact@v4
#        with:
#          name: doc
#          path: doc.pdf
#          overwrite: true
